In [1]:
from pylab import*
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.pyplot import*
from scipy import special
from scipy.stats import multivariate_normal
import pandas as pd
from least_squares_lh import*
from datetime import datetime
from def_conv_crs_1h import*
from def_conv_crs_2h import*
import time 
from datetime import datetime
#warnings.filterwarnings("ignore")
import multiprocessing

/home/zackmrc/Documenti/git_project/SIDIS_epem_git/def_convolution_v3.1_survey_PV17_charm


In [4]:
mean2=array([ 0.17767041, -0.37634992, -0.1206068 , -0.12730992 ,          0.77369741,
  0.84825043,           2.70967305,         1.58986934,
  0.09348547  ])

In [2]:
  cov2=[[ 0.00572,  -0.00323, -0.000304 ,  -0.0046,   0.00732 , 0.000235 ,    0.0658,     0.068,    0.0017],
 [-0.00323  ,  0.0385 , 0.000271 ,  0.00516 ,   -0.0919 , -0.00677 ,    -0.043 ,  -0.0961, -0.000606],
 [-0.000304 , 0.000271,  0.000462 , 0.000284,  -0.00162 ,  -0.0046 ,  -0.00405 , -0.00351, -4.21e-05],
  [ -0.0046 ,  0.00516,  0.000284 ,  0.00403,   -0.0122 ,-0.000801 ,   -0.0518 ,  -0.0606,   -0.0014],
  [ 0.00732 ,  -0.0919,  -0.00162 ,  -0.0122,     0.244 ,   0.0299 ,     0.101 ,    0.198,  0.000933],
  [0.000235 , -0.00677,   -0.0046 ,-0.000801,    0.0299 ,   0.0549 ,   0.00918 ,-0.000948, -0.000658],
  [  0.0658 ,   -0.043,  -0.00405 ,  -0.0518,     0.101 ,  0.00918 ,      0.83 ,    0.824,    0.0176],
  [   0.068 ,  -0.0961,  -0.00351 ,  -0.0606,     0.198 ,-0.000948 ,     0.824 ,     1.03,    0.0196],
  [  0.0017 ,-0.000606, -4.21e-05 ,  -0.0014,  0.000933 ,-0.000658 ,    0.0176 ,   0.0196,  0.000594]]


In [6]:
n_set = 2000
np.random.multivariate_normal(mean2, cov2, n_set).T

array([[ 0.24527085,  0.21902277,  0.26573161, ...,  0.26132967,
         0.09266205,  0.10966004],
       [-0.61519077, -0.21458006, -0.58475303, ..., -0.49971263,
        -0.36117276, -0.48224881],
       [-0.13698761, -0.15484767, -0.08975606, ..., -0.12290935,
        -0.12758898, -0.13539307],
       ...,
       [ 3.24353089,  3.6515792 ,  3.74833606, ...,  3.98052695,
         1.50568343,  1.62207846],
       [ 2.64166977,  1.52444122,  2.68640608, ...,  2.72036742,
         0.52671336,  0.59791458],
       [ 0.11518186,  0.09499025,  0.11331587, ...,  0.11593727,
         0.0692383 ,  0.07265505]])

In [7]:
mean1=array([ 0.14363514, -0.14012427, -0.15129467, -0.08996013,
  2.04589091,            3.57029504,           2.60634211,
  0.09731858  ])

In [8]:
cov1=  [[ 0.00307, -0.000575,  -0.00023,  -0.00234,   0.00028,    0.0438 ,   0.0551,   0.00107],
 [-0.000575 , 0.000312,  -4.7e-05 , 0.000489,  0.000797 , -0.00678 ,  -0.0128 ,-0.000266],
 [ -0.00023 , -4.7e-05,  0.000872 , 0.000157,  -0.00791 , -0.00306 , -0.00152 ,-4.97e-05],
 [ -0.00234 , 0.000489,  0.000157 ,  0.00189,  0.000121 ,  -0.0323 ,   -0.045 ,-0.000872],
 [  0.00028 , 0.000797,  -0.00791 , 0.000121,     0.081 , -0.00203 ,  -0.0308 ,-0.000185],
 [   0.0438 , -0.00678,  -0.00306 ,  -0.0323,  -0.00203 ,    0.695 ,    0.821 ,   0.0133],
 [   0.0551 ,  -0.0128,  -0.00152 ,   -0.045,   -0.0308 ,    0.821 ,     1.18 ,   0.0193],
 [  0.00107 ,-0.000266, -4.97e-05 ,-0.000872, -0.000185 ,   0.0133 ,   0.0193 , 0.000467]]


In [9]:
n_set = 2000
np.random.multivariate_normal(mean1, cov1, n_set).T

array([[ 0.12738951,  0.23066164,  0.07328275, ...,  0.25066377,
         0.17966937,  0.13914605],
       [-0.14334581, -0.16615948, -0.12164028, ..., -0.16381623,
        -0.13409921, -0.1486368 ],
       [-0.1560382 , -0.17352934, -0.15916866, ..., -0.17874697,
        -0.17241806, -0.17014741],
       ...,
       [ 3.19124734,  5.00688751,  2.07544134, ...,  5.23573294,
         4.13864848,  3.76451824],
       [ 2.72920658,  4.31165629,  1.02382431, ...,  4.54505415,
         2.50298893,  2.46151615],
       [ 0.09144195,  0.12163259,  0.07545041, ...,  0.12696035,
         0.09570868,  0.09483944]])

In [10]:
cov3=[[  0.000148, -0.000122, -8.51e-05, -0.000194,  -0.00243,   0.00079,  -0.00895, -0.000698,  0.000136],
 [-0.000122,  0.000329 , 5.04e-05,  0.000163 ,  0.00624, -0.000483 ,   0.0201, -0.000995 , -0.00012],
[-8.51e-05 , 5.04e-05  , 0.00365 , 0.000121  ,-0.00407 ,   -0.0213 ,  -0.0136,  -0.00122 ,-1.01e-05],
[-0.000194 , 0.000163  ,0.000121 , 0.000296  ,  0.0089 ,  -0.00106 ,   0.0293,    0.0012 ,-0.000213],
 [ -0.00243,   0.00624 , -0.00407,    0.0089 ,     1.55,    0.0301 ,     4.67,     0.097 ,  -0.0065],
   [0.00079, -0.000483 ,  -0.0213,  -0.00106 ,   0.0301,     0.136 ,   0.0977,   0.00206 ,   0.0002],
[-0.00895  ,  0.0201   ,-0.0136  ,  0.0293   ,   4.67  ,    0.0977 ,     14.2,     0.314 ,  -0.0215],
 [-0.000698, -0.000995 , -0.00122,    0.0012 ,    0.097,   0.00206 ,    0.314,    0.0765 ,-0.000916],
  [0.000136,  -0.00012 ,-1.01e-05, -0.000213 ,  -0.0065,    0.0002 ,  -0.0215, -0.000916 , 0.000183]]


In [11]:
mean3=array([ 0.13020397, -0.1496972 , -0.2625163,  -0.17407299,  2.83826223,    2.16380442 ,          10.58012192,  1.54487166 
  ,0.11620619    ])

In [12]:
n_set = 2000
np.random.multivariate_normal(mean3, cov3, n_set).T

array([[ 0.15080134,  0.1411027 ,  0.14073124, ...,  0.12836712,
         0.14019391,  0.12973904],
       [-0.14917791, -0.17275303, -0.15712374, ..., -0.15913039,
        -0.17353384, -0.13480466],
       [-0.32374874, -0.25063415, -0.27587549, ..., -0.23572641,
        -0.15168229, -0.31690944],
       ...,
       [ 5.49238567,  8.06658298, 11.76364016, ..., 13.74779728,
         6.49692494, 12.22203324],
       [ 1.30939361,  1.34126195,  1.28361612, ...,  1.50162332,
         1.52864027,  1.97053467],
       [ 0.13980619,  0.12777773,  0.12092598, ...,  0.12332074,
         0.12970901,  0.10370961]])