In [1]:
# -*- coding: utf-8 -*-
from pylab import*
import matplotlib.pyplot as plt
from numpy import*
from matplotlib.pyplot import*
import pandas as pd
import time
import sys
from def_conv_crs_2h import*
from numpy import*
import time 
from datetime import datetime
from matplotlib.legend_handler import HandlerTuple
#scale=10.58
lhapdf.setVerbosity(0)

/home/zackmrc/Documenti/git_project/SIDIS_epem_git/def_convolution_sidis_PV17_beam_en


In [93]:
dfs1 = pd.read_csv('fit_parameters/dfs_/new_gauss_su_charm_no_no_def.csv') 
dfs2 = pd.read_csv('fit_parameters/dfs_/new_gauss_su_charm_no_yes_def.csv')
dfs3 = pd.read_csv('fit_parameters/dfs_/new_gauss_su_charm_yes_yes_def.csv')

df1 = pd.read_csv('fit_parameters/dfs_/fit_hadron_coef_0.27_chi_1.174__True_gk_PV17_su_no_charmno.csv')
df2 = pd.read_csv('fit_parameters/dfs_/fit_hadron_coef_0.27_chi_1.259__True_gk_PV17_su_no_charmyes_correction_no.csv')
df3 = pd.read_csv('fit_parameters/dfs_/fit_hadron_coef_0.27_chi_1.447__True_gk_PV17_su_yes_charmyes.csv')


In [94]:
df1

NUP       NDO       NST      NSEA  AUP  ADO       AST  ASEA       BUP  \
0  0.151081 -0.135165 -0.146546 -0.095736  0.0  0.0  2.060626   0.0  3.834975   

   BDO  BST      BSEA        PP  MSS  coef  chi_sq  
0  0.0  0.0  2.889306  0.103888  0.0  0.27   1.174

In [95]:
dfs1

NUP       NDO       NST      NSEA       AST       BUP      BSEA  \
0     0.179414 -0.154495 -0.134967 -0.114834  1.975072  3.654721  2.948449   
1     0.140092 -0.103588 -0.168640 -0.086923  2.244914  4.199672  2.801611   
2     0.170602 -0.140393 -0.148621 -0.098653  2.142658  4.032842  2.792415   
3     0.131428 -0.144763 -0.135081 -0.084212  2.035190  3.539777  2.889007   
4     0.134546 -0.137666 -0.101932 -0.077150  1.550112  3.829438  2.928802   
...        ...       ...       ...       ...       ...       ...       ...   
1963  0.162036 -0.147861 -0.177139 -0.100254  2.288681  3.865611  2.946237   
1964  0.118966 -0.119035 -0.118783 -0.071224  1.733556  4.002351  2.977212   
1965  0.131575 -0.167733 -0.119713 -0.099209  1.814585  3.010215  2.973223   
1966  0.147982 -0.161057 -0.164618 -0.097140  2.198179  3.588961  2.988108   
1967  0.197821 -0.150155 -0.139488 -0.114708  2.035369  4.031198  2.912394   

           PP2         chi  
0     0.119957  112.500995  
1     0.084528  115.857903  
2     0.114751  117.223654  
3     0.100297  116.806015  
4     0.089877  115.509900  
...        ...         ...  
1963  0.110033  109.349952  
1964  0.078102  116.860152  
1965  0.118235  115.327194  
1966  0.117827  116.462929  
1967  0.118497  114.195029  

[1968 rows x 9 columns]

In [96]:
df1=df1.drop(columns=['AUP', 'ADO','ASEA','BDO','BST','MSS','coef'])
df1

NUP       NDO       NST      NSEA       AST       BUP      BSEA  \
0  0.151081 -0.135165 -0.146546 -0.095736  2.060626  3.834975  2.889306   

         PP  chi_sq  
0  0.103888   1.174

In [97]:
max1=dfs1.max().to_numpy()
min1=dfs1.min().to_numpy()
mean1=df1.values[0]

In [98]:
np.round((max1-mean1),3)

array([7.8000e-02, 3.8000e-02, 5.4000e-02, 3.2000e-02, 8.4900e-01,
       1.1850e+00, 2.9200e-01, 4.6000e-02, 1.1791e+02])

In [99]:
np.round((mean1-min1),3)

array([ 5.20000e-02,  4.60000e-02,  9.00000e-02,  4.90000e-02,
        6.30000e-01,  1.08700e+00,  2.38000e-01,  3.50000e-02,
       -1.03061e+02])

In [100]:
df2

NUP      NDO       NST     NSEA  AUP       ADO      AST  ASEA  \
0  0.17767 -0.37635 -0.120607 -0.12731  0.0  0.773697  0.84825   0.0   

        BUP  BDO  BST      BSEA        PP  MSS  coef  chi_sq  
0  2.709673  0.0  0.0  1.589869  0.093485  0.0  0.27   1.259

In [101]:
df2=df2.drop(columns=['AUP','ASEA','BDO','BST','MSS','coef'])
df2

NUP      NDO       NST     NSEA       ADO      AST       BUP      BSEA  \
0  0.17767 -0.37635 -0.120607 -0.12731  0.773697  0.84825  2.709673  1.589869   

         PP  chi_sq  
0  0.093485   1.259

In [102]:
max2=dfs2.max().to_numpy()
min2=dfs2.min().to_numpy()
mean2=df2.values[0]

In [103]:
np.round((max2-mean2),3)

array([1.67000e-01, 2.53000e-01, 5.00000e-02, 7.60000e-02, 1.17900e+00,
       6.51000e-01, 2.24200e+00, 2.04000e+00, 5.00000e-02, 1.25535e+02])

In [104]:
np.round((mean2-min2),3)

array([ 9.80000e-02,  4.18000e-01,  5.90000e-02,  1.31000e-01,
        7.69000e-01,  6.20000e-01,  1.74900e+00,  1.49900e+00,
        4.60000e-02, -1.09145e+02])

In [105]:
df3

NUP       NDO       NST      NSEA  AUP  ADO       AST  ASEA      BUP  \
0  0.20755 -0.128118 -0.252721 -0.164992  0.0  0.0  2.112447   0.0  2.43826   

        BDO  BST  BSEA        PP  MSS  coef  chi_sq  
0  1.154119  0.0   0.0  0.117157  0.0  0.27   1.447

In [106]:
df3=df3.drop(columns=['AUP','ADO','ASEA','BST','BSEA','MSS','coef'])
df3

NUP       NDO       NST      NSEA       AST      BUP       BDO  \
0  0.20755 -0.128118 -0.252721 -0.164992  2.112447  2.43826  1.154119   

         PP  chi_sq  
0  0.117157   1.447

In [82]:
max3=dfs3.max().to_numpy()
min3=dfs3.min().to_numpy()
mean3=df3.values[0]

In [108]:
np.round((max3-mean3),3)

array([7.20000e-02, 6.50000e-02, 1.08000e-01, 3.70000e-02, 1.11500e+00,
       8.05000e-01, 1.52700e+00, 4.60000e-02, 1.41742e+02])

In [107]:
np.round((mean3-min3),3)

array([ 5.50000e-02,  8.10000e-02,  1.99000e-01,  5.60000e-02,
        8.76000e-01,  8.40000e-01,  1.13100e+00,  3.60000e-02,
       -1.26333e+02])