In [1]:
import numpy as np
import scipy as sc
from least_squares_lh import*
import pandas as pd
#from fitter_v2 import*
import time 
from datetime import datetime
#import warnings
#warnings.filterwarnings("ignore")

In [2]:
df1 = pd.read_csv("fit_parameters/new_gauss_1.csv")
df2 = pd.read_csv("fit_parameters/new_gauss_2.csv")
df3 = pd.read_csv("fit_parameters/new_gauss_3.csv")

In [3]:
df1

NUP       NDO       NST      NSEA       AST       BUP      BSEA  \
0     0.062591 -0.062415 -0.121722 -0.020364  2.343489  3.706220  1.051773   
1     0.053956 -0.076324 -0.113917 -0.027771  2.275214  2.487160  1.029550   
2     0.039662 -0.081988 -0.124499 -0.009283  2.340156  2.499045  0.352765   
3     0.149118 -0.108190 -0.131838 -0.089989  2.366122  5.299178  4.194253   
4     0.106882 -0.101179 -0.094517 -0.059548  1.981996  3.031774  1.790120   
...        ...       ...       ...       ...       ...       ...       ...   
9995  0.137365 -0.108544 -0.138363 -0.084261  2.277759  4.330381  3.445573   
9996  0.076820 -0.082773 -0.153528 -0.031889  2.590777  3.527120  1.335925   
9997  0.069416 -0.083780 -0.135406 -0.029873  2.349309  3.867079  1.821181   
9998  0.099822 -0.100458 -0.137234 -0.040106  2.288954  4.650987  2.561032   
9999  0.107408 -0.109422 -0.112253 -0.077132  2.112454  3.101150  2.931855   

            PP         chi  
0     0.030372  197.490117  
1     0.047980  128.534074  
2     0.031097  264.677690  
3     0.082267  117.022227  
4     0.071176  126.976800  
...        ...         ...  
9995  0.086827  115.278099  
9996  0.051980  129.836212  
9997  0.043875  121.781480  
9998  0.047976  122.749820  
9999  0.085484  117.004437  

[10000 rows x 9 columns]

In [4]:
df1['chi'].min()



105.56320202304266

In [5]:
df2['chi'].min()


105.61790328309435

In [6]:
df3['chi'].min()


105.53763505439859

In [7]:
frames = [df1, df2, df3]
result = pd.concat(frames)

In [8]:
result

NUP       NDO       NST      NSEA       AST       BUP      BSEA  \
0     0.062591 -0.062415 -0.121722 -0.020364  2.343489  3.706220  1.051773   
1     0.053956 -0.076324 -0.113917 -0.027771  2.275214  2.487160  1.029550   
2     0.039662 -0.081988 -0.124499 -0.009283  2.340156  2.499045  0.352765   
3     0.149118 -0.108190 -0.131838 -0.089989  2.366122  5.299178  4.194253   
4     0.106882 -0.101179 -0.094517 -0.059548  1.981996  3.031774  1.790120   
...        ...       ...       ...       ...       ...       ...       ...   
9995  0.136182 -0.113659 -0.120108 -0.082827  2.205212  4.675591  3.605045   
9996  0.027732 -0.076938 -0.084230  0.003322  1.840950  1.805088 -0.495292   
9997  0.104178 -0.102820 -0.125254 -0.059802  2.311877  3.613318  2.624995   
9998  0.094698 -0.092066 -0.151932 -0.052106  2.478436  3.803593  2.385419   
9999  0.083089 -0.104073 -0.086563 -0.058394  1.648943  2.949039  2.403893   

            PP         chi  
0     0.030372  197.490117  
1     0.047980  128.534074  
2     0.031097  264.677690  
3     0.082267  117.022227  
4     0.071176  126.976800  
...        ...         ...  
9995  0.081895  108.734727  
9996  0.032283         NaN  
9997  0.063880  112.036703  
9998  0.055505  110.300195  
9999  0.075218  113.257746  

[30000 rows x 9 columns]

In [9]:
chi_min = 104.9
chi_delta2 =  15.79
chi_delta1 =  9.3


In [10]:
df1=df1.loc[(df1['chi']<chi_min + chi_delta2)]
df2=df2.loc[(df2['chi']<chi_min + chi_delta2)]
df3=df3.loc[(df3['chi']<chi_min + chi_delta2)]

In [11]:
df3

NUP       NDO       NST      NSEA       AST       BUP      BSEA  \
1     0.140884 -0.106873 -0.155990 -0.089224  2.440075  4.840372  3.850086   
2     0.133693 -0.102555 -0.123399 -0.094440  2.086251  3.897823  3.492501   
3     0.070971 -0.097165 -0.101612 -0.042595  2.075771  2.947817  1.708930   
5     0.105738 -0.114876 -0.110789 -0.080619  2.035989  3.235786  3.026861   
6     0.085165 -0.080988 -0.133381 -0.044034  2.364311  4.206352  2.345569   
...        ...       ...       ...       ...       ...       ...       ...   
9993  0.117789 -0.113523 -0.106511 -0.077461  1.892973  3.684171  3.171720   
9995  0.136182 -0.113659 -0.120108 -0.082827  2.205212  4.675591  3.605045   
9997  0.104178 -0.102820 -0.125254 -0.059802  2.311877  3.613318  2.624995   
9998  0.094698 -0.092066 -0.151932 -0.052106  2.478436  3.803593  2.385419   
9999  0.083089 -0.104073 -0.086563 -0.058394  1.648943  2.949039  2.403893   

            PP         chi  
1     0.082527  113.664046  
2     0.090379  117.695060  
3     0.058413  110.810670  
5     0.084675  109.117752  
6     0.043678  114.538373  
...        ...         ...  
9993  0.079495  111.244656  
9995  0.081895  108.734727  
9997  0.063880  112.036703  
9998  0.055505  110.300195  
9999  0.075218  113.257746  

[6656 rows x 9 columns]

In [12]:
result=result.loc[(result['chi']<chi_min + chi_delta2)]


In [13]:
result

NUP       NDO       NST      NSEA       AST       BUP      BSEA  \
3     0.149118 -0.108190 -0.131838 -0.089989  2.366122  5.299178  4.194253   
6     0.090651 -0.119123 -0.095107 -0.057717  1.876391  3.065144  2.332393   
7     0.089647 -0.107668 -0.141213 -0.052345  2.373271  3.433331  2.656243   
8     0.132422 -0.118279 -0.123038 -0.086174  2.285229  4.017368  3.195718   
9     0.083777 -0.097032 -0.162423 -0.048726  2.888242  2.925329  1.855780   
...        ...       ...       ...       ...       ...       ...       ...   
9993  0.117789 -0.113523 -0.106511 -0.077461  1.892973  3.684171  3.171720   
9995  0.136182 -0.113659 -0.120108 -0.082827  2.205212  4.675591  3.605045   
9997  0.104178 -0.102820 -0.125254 -0.059802  2.311877  3.613318  2.624995   
9998  0.094698 -0.092066 -0.151932 -0.052106  2.478436  3.803593  2.385419   
9999  0.083089 -0.104073 -0.086563 -0.058394  1.648943  2.949039  2.403893   

            PP         chi  
3     0.082267  117.022227  
6     0.069731  115.946851  
7     0.061326  112.448154  
8     0.094750  111.373823  
9     0.058977  116.169681  
...        ...         ...  
9993  0.079495  111.244656  
9995  0.081895  108.734727  
9997  0.063880  112.036703  
9998  0.055505  110.300195  
9999  0.075218  113.257746  

[19983 rows x 9 columns]

In [14]:
#plt.hist(result.chi,bins=200)

In [15]:
dati_lp = pd.read_csv("set_bande_pols/dati_lp_flh.csv")


In [16]:
dati_lp['z1']

0      0.25
1      0.25
2      0.25
3      0.25
4      0.25
       ... 
235    0.60
236    0.60
237    0.60
238    0.60
239    0.60
Name: z1, Length: 240, dtype: float64

In [17]:
dati_lp.loc[(dati_lp['z1']==0.25) & (dati_lp['had1']==300) & (dati_lp['had2']==100) ]

had1   had2    z1        z2      mins      maxx  fit_line
0   300.0  100.0  0.25  0.150000 -0.024188 -0.015832 -0.019969
1   300.0  100.0  0.25  0.203571 -0.034641 -0.024036 -0.029360
2   300.0  100.0  0.25  0.257143 -0.044604 -0.031931 -0.038314
3   300.0  100.0  0.25  0.310714 -0.053621 -0.039167 -0.046510
4   300.0  100.0  0.25  0.364286 -0.061877 -0.045759 -0.054074
5   300.0  100.0  0.25  0.417857 -0.070156 -0.052025 -0.061512
6   300.0  100.0  0.25  0.471429 -0.078654 -0.058440 -0.069094
7   300.0  100.0  0.25  0.525000 -0.087769 -0.065334 -0.077232
8   300.0  100.0  0.25  0.578571 -0.097604 -0.072718 -0.086021
9   300.0  100.0  0.25  0.632143 -0.108081 -0.080595 -0.095389
10  300.0  100.0  0.25  0.685714 -0.119245 -0.088799 -0.105173
11  300.0  100.0  0.25  0.739286 -0.130530 -0.096985 -0.115023
12  300.0  100.0  0.25  0.792857 -0.141744 -0.105023 -0.124694
13  300.0  100.0  0.25  0.846429 -0.152533 -0.112748 -0.133989
14  300.0  100.0  0.25  0.900000 -0.162928 -0.120194 -0.142946

In [18]:
z2s = linspace(0.15,0.8,10)
z2s=around(z2s,3)

In [19]:
around(z2s,3)

array([0.15 , 0.222, 0.294, 0.367, 0.439, 0.511, 0.583, 0.656, 0.728,
       0.8  ])

In [20]:
dati_lp

had1   had2    z1        z2      mins      maxx  fit_line
0    300.0  100.0  0.25  0.150000 -0.024188 -0.015832 -0.019969
1    300.0  100.0  0.25  0.203571 -0.034641 -0.024036 -0.029360
2    300.0  100.0  0.25  0.257143 -0.044604 -0.031931 -0.038314
3    300.0  100.0  0.25  0.310714 -0.053621 -0.039167 -0.046510
4    300.0  100.0  0.25  0.364286 -0.061877 -0.045759 -0.054074
..     ...    ...   ...       ...       ...       ...       ...
235  310.0  105.0  0.60  0.685714 -0.090058 -0.063380 -0.076762
236  310.0  105.0  0.60  0.739286 -0.100629 -0.068506 -0.084714
237  310.0  105.0  0.60  0.792857 -0.112909 -0.074045 -0.093754
238  310.0  105.0  0.60  0.846429 -0.127691 -0.079869 -0.104251
239  310.0  105.0  0.60  0.900000 -0.145826 -0.085811 -0.116854

[240 rows x 7 columns]

In [21]:
clm=dati_lp.columns
df_lp=pd.DataFrame(columns=clm)
df_lk=pd.DataFrame(columns=clm)


In [22]:
df_lp

Empty DataFrame
Columns: [had1, had2, z1, z2, mins, maxx, fit_line]
Index: []

In [23]:
hads1=zeros(8*len(z2s))+300
hads11= zeros(8*len(z2s))+310
had1_n=np.concatenate((hads1,hads11))

In [24]:
len(had1_n)
had1_n

array([300., 300., 300., 300., 300., 300., 300., 300., 300., 300., 300.,
       300., 300., 300., 300., 300., 300., 300., 300., 300., 300., 300.,
       300., 300., 300., 300., 300., 300., 300., 300., 300., 300., 300.,
       300., 300., 300., 300., 300., 300., 300., 300., 300., 300., 300.,
       300., 300., 300., 300., 300., 300., 300., 300., 300., 300., 300.,
       300., 300., 300., 300., 300., 300., 300., 300., 300., 300., 300.,
       300., 300., 300., 300., 300., 300., 300., 300., 300., 300., 300.,
       300., 300., 300., 310., 310., 310., 310., 310., 310., 310., 310.,
       310., 310., 310., 310., 310., 310., 310., 310., 310., 310., 310.,
       310., 310., 310., 310., 310., 310., 310., 310., 310., 310., 310.,
       310., 310., 310., 310., 310., 310., 310., 310., 310., 310., 310.,
       310., 310., 310., 310., 310., 310., 310., 310., 310., 310., 310.,
       310., 310., 310., 310., 310., 310., 310., 310., 310., 310., 310.,
       310., 310., 310., 310., 310., 310., 310., 31

In [25]:
hads2=zeros(4*len(z2s))+100
hads22=zeros(4*len(z2s))+105
had_2=np.concatenate((hads2,hads22))
had_2=np.concatenate((had_2,had_2))
had_2

array([100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 105., 105., 105., 105.,
       105., 105., 105., 105., 105., 105., 105., 105., 105., 105., 105.,
       105., 105., 105., 105., 105., 105., 105., 105., 105., 105., 105.,
       105., 105., 105., 105., 105., 105., 105., 105., 105., 105., 105.,
       105., 105., 105., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 105.,
       105., 105., 105., 105., 105., 105., 105., 105., 105., 105., 105.,
       105., 105., 105., 105., 105., 105., 105., 105., 105., 105., 105.,
       105., 105., 105., 105., 105., 105., 105., 10

In [26]:
zs1=zeros(len(z2s))+0.25
zs11=zeros(len(z2s))+0.35
zs111=zeros(len(z2s))+0.45
zs1111=zeros(len(z2s))+0.6
zs1_n=np.concatenate((zs1,zs11,zs111,zs1111))
zs1_n=np.concatenate((zs1_n,zs1_n,zs1_n,zs1_n))

In [27]:
z2s
z2s_n=np.concatenate((z2s,z2s,z2s,z2s,z2s,z2s,z2s,z2s))
z2s_n=np.concatenate((z2s_n,z2s_n))

In [28]:
df_lp['had1']=had1_n
df_lp['had2']=had_2
df_lp['z1'] = zs1_n
df_lp['z2'] = z2s_n

In [29]:
df_lp

had1   had2    z1     z2 mins maxx fit_line
0    300.0  100.0  0.25  0.150  NaN  NaN      NaN
1    300.0  100.0  0.25  0.222  NaN  NaN      NaN
2    300.0  100.0  0.25  0.294  NaN  NaN      NaN
3    300.0  100.0  0.25  0.367  NaN  NaN      NaN
4    300.0  100.0  0.25  0.439  NaN  NaN      NaN
..     ...    ...   ...    ...  ...  ...      ...
155  310.0  105.0  0.60  0.511  NaN  NaN      NaN
156  310.0  105.0  0.60  0.583  NaN  NaN      NaN
157  310.0  105.0  0.60  0.656  NaN  NaN      NaN
158  310.0  105.0  0.60  0.728  NaN  NaN      NaN
159  310.0  105.0  0.60  0.800  NaN  NaN      NaN

[160 rows x 7 columns]

In [30]:
hads2=zeros(4*len(z2s))+200
hads22=zeros(4*len(z2s))+205
had_2=np.concatenate((hads2,hads22))
had_2=np.concatenate((had_2,had_2))
had_2

array([200., 200., 200., 200., 200., 200., 200., 200., 200., 200., 200.,
       200., 200., 200., 200., 200., 200., 200., 200., 200., 200., 200.,
       200., 200., 200., 200., 200., 200., 200., 200., 200., 200., 200.,
       200., 200., 200., 200., 200., 200., 200., 205., 205., 205., 205.,
       205., 205., 205., 205., 205., 205., 205., 205., 205., 205., 205.,
       205., 205., 205., 205., 205., 205., 205., 205., 205., 205., 205.,
       205., 205., 205., 205., 205., 205., 205., 205., 205., 205., 205.,
       205., 205., 205., 200., 200., 200., 200., 200., 200., 200., 200.,
       200., 200., 200., 200., 200., 200., 200., 200., 200., 200., 200.,
       200., 200., 200., 200., 200., 200., 200., 200., 200., 200., 200.,
       200., 200., 200., 200., 200., 200., 200., 200., 200., 200., 205.,
       205., 205., 205., 205., 205., 205., 205., 205., 205., 205., 205.,
       205., 205., 205., 205., 205., 205., 205., 205., 205., 205., 205.,
       205., 205., 205., 205., 205., 205., 205., 20

In [31]:
df_lk['had1']=had1_n
df_lk['had2']=had_2
df_lk['z1'] = zs1_n
df_lk['z2'] = z2s_n

In [32]:
df_lk

had1   had2    z1     z2 mins maxx fit_line
0    300.0  200.0  0.25  0.150  NaN  NaN      NaN
1    300.0  200.0  0.25  0.222  NaN  NaN      NaN
2    300.0  200.0  0.25  0.294  NaN  NaN      NaN
3    300.0  200.0  0.25  0.367  NaN  NaN      NaN
4    300.0  200.0  0.25  0.439  NaN  NaN      NaN
..     ...    ...   ...    ...  ...  ...      ...
155  310.0  205.0  0.60  0.511  NaN  NaN      NaN
156  310.0  205.0  0.60  0.583  NaN  NaN      NaN
157  310.0  205.0  0.60  0.656  NaN  NaN      NaN
158  310.0  205.0  0.60  0.728  NaN  NaN      NaN
159  310.0  205.0  0.60  0.800  NaN  NaN      NaN

[160 rows x 7 columns]

In [33]:
df_lk.loc[(df_lk['z1']==0.25) & (df_lk['had1']==310) & (df_lk['had2']==200) ]

had1   had2    z1     z2 mins maxx fit_line
80  310.0  200.0  0.25  0.150  NaN  NaN      NaN
81  310.0  200.0  0.25  0.222  NaN  NaN      NaN
82  310.0  200.0  0.25  0.294  NaN  NaN      NaN
83  310.0  200.0  0.25  0.367  NaN  NaN      NaN
84  310.0  200.0  0.25  0.439  NaN  NaN      NaN
85  310.0  200.0  0.25  0.511  NaN  NaN      NaN
86  310.0  200.0  0.25  0.583  NaN  NaN      NaN
87  310.0  200.0  0.25  0.656  NaN  NaN      NaN
88  310.0  200.0  0.25  0.728  NaN  NaN      NaN
89  310.0  200.0  0.25  0.800  NaN  NaN      NaN

In [34]:
df_lp.to_csv(r'fit_parameters/lp_point')

df_lk.to_csv(r'fit_parameters/lk_point')

In [35]:
df1 = pd.read_csv("fit_parameters/new_gauss_1.csv")
df2 = pd.read_csv("fit_parameters/new_gauss_2.csv")
df3 = pd.read_csv("fit_parameters/new_gauss_3.csv")
frames = [df1, df2, df3]
result = pd.concat(frames)
result = result.loc[(result['chi'] <104.9 + 15.79)]
#result.to_csv(r'fit_parameters/new_gauss_tot.csv')

In [36]:
result

NUP       NDO       NST      NSEA       AST       BUP      BSEA  \
3     0.149118 -0.108190 -0.131838 -0.089989  2.366122  5.299178  4.194253   
6     0.090651 -0.119123 -0.095107 -0.057717  1.876391  3.065144  2.332393   
7     0.089647 -0.107668 -0.141213 -0.052345  2.373271  3.433331  2.656243   
8     0.132422 -0.118279 -0.123038 -0.086174  2.285229  4.017368  3.195718   
9     0.083777 -0.097032 -0.162423 -0.048726  2.888242  2.925329  1.855780   
...        ...       ...       ...       ...       ...       ...       ...   
9993  0.117789 -0.113523 -0.106511 -0.077461  1.892973  3.684171  3.171720   
9995  0.136182 -0.113659 -0.120108 -0.082827  2.205212  4.675591  3.605045   
9997  0.104178 -0.102820 -0.125254 -0.059802  2.311877  3.613318  2.624995   
9998  0.094698 -0.092066 -0.151932 -0.052106  2.478436  3.803593  2.385419   
9999  0.083089 -0.104073 -0.086563 -0.058394  1.648943  2.949039  2.403893   

            PP         chi  
3     0.082267  117.022227  
6     0.069731  115.946851  
7     0.061326  112.448154  
8     0.094750  111.373823  
9     0.058977  116.169681  
...        ...         ...  
9993  0.079495  111.244656  
9995  0.081895  108.734727  
9997  0.063880  112.036703  
9998  0.055505  110.300195  
9999  0.075218  113.257746  

[19983 rows x 9 columns]

In [37]:
dff1 = pd.read_csv("fit_parameters/new_pwrlw_1.csv")
dff2 = pd.read_csv("fit_parameters/new_pwrlw_2.csv")
dff3 = pd.read_csv("fit_parameters/new_pwrlw_3.csv")
frames = [dff1, dff2, dff3]
result = pd.concat(frames)
result = result.loc[(result['chi'] <105.3 + 17.21)]
#result.to_csv(r'fit_parameters/new_pwrlw_tot.csv')

In [38]:
result

NUP       NDO       NST      NSEA       AST       BUP      BSEA  \
0     0.070685 -0.125027 -0.139920 -0.053751  2.367967  2.289423  2.180724   
1     0.118836 -0.108259 -0.117950 -0.064022  2.242666  3.730990  2.159513   
4     0.082274 -0.105023 -0.093968 -0.042599  1.865687  3.377874  1.977735   
5     0.093960 -0.110581 -0.111972 -0.054606  2.215653  3.231981  2.226817   
6     0.113745 -0.112025 -0.110415 -0.056882  2.067580  3.958231  2.215379   
...        ...       ...       ...       ...       ...       ...       ...   
9992  0.077387 -0.095296 -0.158609 -0.043319  2.936789  2.706648  1.315272   
9993  0.140084 -0.121162 -0.146930 -0.088473  2.425067  4.164973  3.165562   
9995  0.083630 -0.094908 -0.101789 -0.055900  1.969057  3.178339  2.293204   
9996  0.108065 -0.106240 -0.119952 -0.067212  2.108771  3.536769  2.668100   
9999  0.117416 -0.100624 -0.113467 -0.061298  2.078871  4.605653  2.938053   

            PP       MSS         chi  
0     2.875632  0.349696  118.610432  
1     3.582930  0.432090  108.958479  
4     3.127360  0.335863  109.860786  
5     3.479964  0.379040  109.233254  
6     3.732947  0.436757  109.868854  
...        ...       ...         ...  
9992  3.913881  0.411182  120.148582  
9993  2.950581  0.423396  118.945666  
9995  3.827004  0.417949  110.692657  
9996  4.018282  0.468781  109.955201  
9999  3.223536  0.328521  112.140801  

[16789 rows x 10 columns]

In [42]:
result['chi'].min()


105.66025097322915

In [2]:
df1 = pd.read_csv("fit_parameters/new_gauss_1.csv")
df2 = pd.read_csv("fit_parameters/new_gauss_2.csv")
df3 = pd.read_csv("fit_parameters/new_gauss_3.csv")
frames = [df1, df2, df3]
result = pd.concat(frames)
df1_n = result.loc[(df1['chi'] <104.9 + 15.79)]
df2_n = result.loc[(df2['chi'] <104.9 + 15.79)]
df3_n = result.loc[(df3['chi'] <104.9 + 15.79)]

#result.to_csv(r'fit_parameters/new_gauss_tot.csv')

In [3]:
df1_n.to_csv(r'fit_parameters/new_gauss_chi_1.csv')
df2_n.to_csv(r'fit_parameters/new_gauss_chi_2.csv')
df3_n.to_csv(r'fit_parameters/new_gauss_chi_3.csv')